### ISSUE TITLE
Change Event for nested collection not triggered

### ISSUE THREAD

**Issue by toytonic** [dhruvaray/backbone-associations#138]
Hi,
first of all thanks for your great plugin.

I am currently having problems with an associated model having a nested collection. So far I don't get any change event when the whole collection is changed or replaced. Could well be that I am following a wrong practice, so I am happy if you point me in the right direction.

I created a jsFiddle to demonstration: http://jsfiddle.net/CucbF/

Thanks for looking into it...

Cheers!

**Comment by toytonic** [comment]
Hi, did you have a chance to look into the fiddle I provided?

Would be appreciated a lot ;)

**Comment by dhruvaray** [comment]
@toytonic : Apologies for the delay in response. See issue #67 and #31 for background on why we don't create a fresh instance of a collection on replace.

A modified version of your fiddle is [here](http://jsfiddle.net/dhruvaray/qpmXR/). 

The gist is:

The `change:locations` fires for the first time because there is nothing assigned to the collection. The next time you `set` a different collection, we do a smart set on the existing collection models. The reason to do a smart set (rather than a replace) is to allow previously defined event handlers to continue working. You could pass reset:true in options to get notified that the collection has had a smart replace. See the fiddle for details.

**Comment by toytonic** [comment]
No problem and thanks for your answer. Makes total sense to me.
