### ISSUE TITLE
Support for Polymorphic Associate

### ISSUE THREAD

**Issue by allenwyma** [dhruvaray/backbone-associations#23]
I need to use a polymorphic associate, is there a way to do this?

**Comment by dhruvaray** [comment]
Can you elaborate on what you are looking for? Preferably with some pseudo code.

**Comment by allenwyma** [comment]
Yes, actually I have a class of Job that belongs to either a Department or Company. It has a rails backend, so polymorphic associations work by adding a _id and _type fields. In this case it's organizable_id and organizable_type. If the organizable_type == "Company", then it's a Company model and the organizable_id would be the ID of the model inside of the companies table; vice versa for Department.

**Comment by dhruvaray** [comment]
If we assume for a moment that we don't have the problem of mapping object/associations to a relational structure (that's my first cut read of polymorphic associations at the Ruby layer), then at the JavaScript layer, you could probably get what you want like [this](http://jsfiddle.net/dhruvaray/9vxa8/). If it is really useful, we could easily add a `parents` property to any AssociatedModel which would list out who all point to this [Noun]able object

**Comment by allenwyma** [comment]
Yeah, that part is very easy to do, but I'm usually going from the job to the organizable (Company or Department). So I pull a bunch of users, they have a key of jobs, the jobs is an array of Job objects, and the job will belong to a Company or Department. So, doing the way you told me is easy, but going the other way around is a bit more difficult.

**Comment by dhruvaray** [comment]
Yes, It is. We effectively want to say that the `relatedModel` is a trait/mixin but can actually contain any object (not necessarily related via inheritance) which has that trait. I'll think on how to achieve this.

**Comment by wyuenho** [comment]
I'm interested in this feature as well.

**Comment by dhruvaray** [comment]
With backbone-associations v0.5.0, you could implement the concept as demonstrated in this [gist](https://gist.github.com/dhruvaray/5874290). Any suggestions on the API (or otherwise) would be welcome.

**Comment by sgrif** [comment]
Why not just allow relatedModel to be a function, and call it for each model if it is?

**Comment by dhruvaray** [comment]
It is possible to make `relatedModel` take in a function as well... But how would that help support polymorphic associates?

**Comment by sgrif** [comment]
So for @HangingClowns example, the association would look like this (assuming the models in JS are named the same as his Rails app, and are under the 'Models' module)

``` coffeescript
class Models.Job extend Backbone.AssociatedModel
  relations: [
    {
      type: Backbone.One
      key: 'organizable'
      relatedModel: -> Models[@get('organizable_type')]
    }
  ]
```

Backbone associations doesn't need to care about how we map various classes, or what keys are being used, or anything else that might change from app to app or back-end to back-end, it just needs to know that if `relatedModel` is a function, the association might be a different class for each reference.

**Comment by sgrif** [comment]
Also for anyone not familiar with CoffeeScript:

``` javascript
var Models.Job = Backbone.AssociatedModel.extend({
  relations: [
    {
      type: Backbone.One,
      key: 'organizable',
      relatedModel: function() {
        return Models[this.get('organizable_type')];
      }
    }
  ]
});
```

**Comment by dhruvaray** [comment]
@sgrif : Thanks for the clarification and code snippet. That helped indeed! 

The edge version now allows `relatedModel`s to also be a function. Your example is captured in the test suite [here](https://github.com/dhruvaray/backbone-associations/commit/5210ae85d3b441384aa378356c02e31d538ff0ce#L1R878)

Note that the function which computes the `relatedModel` would need the current hash of attributes (passed to the `set` method) to be also passed to it. Otherwise the computed value from the function would either be undefined - like in this example - or stale.

``` javascript
var cjob = new Models.Job({organizable_type:'Company', name:"J1", organizable:{name:"Google"}});

//relatedModel() computation would return undefined as
//this.get('organizable_type') has not yet been set.
```

The following definition should overcome the problem. The passed in `attributes` is the new set of values _to-be-assigned_ to the `Job` instance

``` javascript
Models.Job = Backbone.AssociatedModel.extend({
    relations:[
        {
            type:Backbone.One,
            key:'organizable',
            relatedModel:function (attributes) {
                return Models[attributes['organizable_type'] || this.get('organizable_type')];
            }
        }
    ]

});
```

**Comment by sgrif** [comment]
Could we do something like this to avoid the need for that ugly `||` in the consumer code?

``` javascript
  newAttributes = _.extend(_.clone(this.attributes), attributes);
  relatedModel.call(this, newAttributes);
```

**Comment by monokrome** [comment]
Doesn't backbone associations contain a map of all the models already? Can't that be passed to the function?

```
relatedModel: function (models, attributes) {
    return models[attributes['organizable_type']];
}
```

That'd be better assuming that associations is already keeping a list of models. It's not guaranteed in applications that everything is in one huge Models list.

I'd hope that organizableType is an assumed API-specific implementation detail, and not some special thing?

IE, there are other use cases. I came across this issue regarding a response that I need to use which is similar to the following link:

https://gist.github.com/monokrome/5953738

I would hope that I could also do things like filtering through models for any model where resourceURI starts with urlRoot and then decide which model to use based on whatever result is the closest match to that.

**Comment by sgrif** [comment]
Brandon, that example is in the consumer code, not in backbone
associations. The idea is that it doesn't know where you keep your models,
you tell it.

On Mon, Jul 8, 2013 at 7:02 PM, Brandon R. Stoner
notifications@github.comwrote:

> Doesn't backbone associations contain a map of all the models already?
> Can't that be passed to the function?
> 
> relatedModel: function (models, attributes) {
>     return models[attributes['organizable_type'] || || this.get('organizable_type')];
> }
> 
> That'd be better assuming that associations is already keeping a list of
> models. It's not guaranteed in applications that everything is in one huge
> Models list.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/dhruvaray/backbone-associations/issues/23#issuecomment-20647210
> .

## 

Thanks,
Sean Griffin

**Comment by monokrome** [comment]
Understood, but doesn't Backbone associations already have a cached list of models that exist in order to do relations to strings and such?

**Comment by sgrif** [comment]
I'm afraid you've lost me.

**Comment by monokrome** [comment]
If I understand correctly, backbone-associations' `map2Scope` function uses a map that caches all of the models to figure out what model the string you've provided as a relation represents. My question is that - if you already have a cached list of all the models - why not just provide that as an argument to the relation function?

It avoids the necessity of getting references to all sorts of models, which could become more work as the number of models in the project increases - especially in terms of resources which could potentially represent a generic association.

**Comment by sgrif** [comment]
So first of all, I'm not sure where you're seeing caching. There is none happening in that method. What that seems to be there for is taking a string like `'App.Models.Foo'` and turning that into `App['Models']['Foo']` (or `App.Models.Foo` if you prefer.

That's not what we're doing with polymorphic associations here. The way a polymorphic association works in Ruby on Rails is that you have 2 columns, type, and id, with type being the name of the Ruby class. Of course we can't assume that all back ends will handle polymorphism like Rails, but it's a pretty simple case, so we'll use that as the example. Let's pretend you had an app with a data structure like this:

``` ruby
class Comment < ActiveRecord::Base
  belongs_to :commentable, polymorphic: true
end

class Article < ActiveRecord::Base
  has_one :comment, as: :commentable
end

class StatusUpdate < ActiveRecord::Base
  has_one :comment, as: :commentable
end
```

so with that structure, /comments.json would look like this:

``` javascript
[
  {
    title: 'Wow that was a great article!',
    body: 'I really enjoyed reading it.',
    commentable_id: 1,
    commentable_type: 'Article',
    commentable: {
      // article's attributes...
    }
  },
  {
    title: 'Cool story bro',
    body: 'Why are you updating your status with pointless crap?',
    commentable_id: 1,
    commentable_type: 'StatusUpdate',
    commentable: {
      // status update's attributes...
    }
  }
]
```

Now, if your backbone app follows the structure used in Thoughtbot's book Backbone JS on Rails, your models in Backbone likely follow one-to-one naming with your ruby models, and are scoped to `App.Models`, so you'd have `App.Models.Comment = Backbone.AssociatedModel.extend({...})`, `App.Models.Article = Backbone.AssociatedModel.extend({...})`, and so on. In that case, the code would be as simple as the example I gave above.

However, that may not be the case for your app. Maybe in your structure, Commentable type is an integer, and you map it that way. One thing that is fairly certain though, is that it won't be a string containing your Backbone model, nor should it. That's presentation logic.

I'd also like to point out that there isn't any real computation happening in the code I gave above. It's accessing a variable. If the result of that was "cached", the code to retrieve the cached value would be virtually identical.

Hopefully this clarifies things a bit.

**Comment by monokrome** [comment]
I thought that there was some caching, so since it's not there then the answer to my question is no. Thanks for the description. :)

**Comment by dhruvaray** [comment]
@sgrif  : I agree with your comment on the need to remove the ugly `||` in the consumer code. The idea in your code snippet is neat. However, some thoughts.
- All attribute values are not of primitive type. They could contain sub-graphs rooted at that attribute. 
- Due to this, it is possible that a specific attribute value (already present in the existing instance) is an `AssociatedModel`,but what is passed in (via `set`) is a simple JavaScript object graph (which will eventually get turned into a AssociatedModel based on the `relatedModel`). 

So, if we do what you suggest, the consumer code may have to check whether it is an instance of an `AssociatedModel` or a raw hash. So the complexity remains - in some sense.

@monokrome : @sgrif  is right about the map2scope implementation. Backbone-associations does _NO_ kind of caching. It would make the library unnecessarily complicated. Additionally, I would not even know when to clear the cache. And that would cause memory bloat on the consumer end.

**Comment by sgrif** [comment]
Hm... My gut reaction is to say that the best solution would be to ensure that all non-association keys are set before we handle associations, and that the consumer can always rely on `this.get`. I'm not sure if that would be possible to implement cleanly, however. 

If it's alright with you, I'm going to spend an hour or two some time a few days familiarizing myself with the code base, and submit a PR this weekend.

**Comment by monokrome** [comment]
@dhruvaray I agree that caching is unnecessarily complicated. I had thought that it was already there, but that's in backbone-relational (and it causes many issues in that library).

I would like to mention that it'd be nice if the relation was passed to this function after attributes, however - because there's no way to know what relation you are working with in the case of generic functions that handle polymorphic associations. For instance, here's an example:

https://gist.github.com/monokrome/5954751

See #50 for a pull request.

**Comment by dhruvaray** [comment]
@sgrif  : The danger with doing that could be that the `change` events fire prematurely - before the entire graph has been updated. So event handlers would land up with an intermediate (partially - updated) object hierarchy. Nonetheless, maybe there is a way around it. So I'll wait for your PR to see what you are thinking!

**Comment by dhruvaray** [comment]
@monokrome : Fair enough. I agree. Would you be so kind to also put in a test case (or update the existing [one](https://github.com/dhruvaray/backbone-associations/commit/5210ae85d3b441384aa378356c02e31d538ff0ce#L1R878)) as part of the pull request. Also, I would probably change the order of the arguments to > relation, attributes.

**Comment by monokrome** [comment]
@dhruvaray I was thinking that the attributes are probably more often useful than the relation itself, but changing the order wouldn't be a problem if you disagree.

**Comment by monokrome** [comment]
@dhruvaray A test case has been added. I'm not very familiar with whatever testing framework is being used, so let me know if this was an odd method of testing the feature.

**Comment by dhruvaray** [comment]
@monokrome : I just thought meta data (this, relation) before data (attributes)...

**Comment by monokrome** [comment]
@dhruvaray 

Are you saying to just pass in a meta object instead? IE, something like:

```
{
    "attributes": attributes,
    "relation": relation
}
```

That could work, but I don't know if it's really _better_ than passing it in as the first argument.

The `attributes` object is really always necessary since the data in this.attributes is not guaranteed to be fresh, so it's going to need to be passed every time. Function arguments seem like a sound method for doing that, and passing it as a reference to the function doesn't require that new objects be thrown together for every relation in the parsed data.

Maybe I'm missing something, but the current solution seems like the right one. Hopefully along with also passing the relation as the second argument (since it's not always necessary like `attributes` is, but can be quite useful when it is) like #50 suggests.

Passing around objects is nice when you have huge monolithic objects that need to get around, but the requirements here leave a pretty small footprint.

**Comment by dhruvaray** [comment]
oops... no. that's not what I meant !

I was just commenting on why I thought having relation as a first parameter (and then attributes) would be a better idea

> > @dhruvaray I was thinking that the attributes are probably more often useful than the relation itself, but changing >>the order wouldn't be a problem if you disagree.

**Comment by dhruvaray** [comment]
@monokrome  : I accepted your PR and switched the params around. Otherwise you should have what you needed.

**Comment by monokrome** [comment]
@dhruvaray Cool. Just saw all the updatess. Had to get some sleep last night. Thanks!

**Comment by dhruvaray** [comment]
See recipes [here](http://dhruvaray.github.io/backbone-associations/recipes.html#tut-pa) and [here](http://dhruvaray.github.io/backbone-associations/recipes.html#tut-map2) in the project documentation.
