### ISSUE TITLE
Changed association does not reflect in #changedAttributes

### ISSUE THREAD

**Issue by wprater** [dhruvaray/backbone-associations#34]
Why is it that when I add an association, I cannot see the changed attributes?

```
p = new Project
>> Project {cid: "c21", attributes: Object, _changing: false, _previousAttributes: Object, changed: Object…}
p.changedAttributes()
>> false
p.get('users').add(u)
>> Backbone.Collection {length: 1, models: Array[1], _byId: Object, model: function, _proxyCallback: function…}
p.changedAttributes()
>> false
```

**Comment by dhruvaray** [comment]
This is because the memory reference to `users` in `Project` model has NOT 'changed'. You haven't really assigned a new `users` collection to `Project`. (which would trigger the behavior you are expecting) An _existing_ `users` collection is retrieved and a new `user` is added to the _existing_ collection. You can listen in to that event via 

``` javascript
p.on('add:users', function () {
        console.log("Added an user...");
 });

```

Hope that makes it clear.

**Comment by wprater** [comment]
Thanks, that does make it clear, however, now I have to manage all the changed relations manually.  Because when I issue a patch with Backbone#sync, I only send the changed attributes.

**Comment by dhruvaray** [comment]
Can you post a jsfiddle or some pseudo-code of what you are attempting to do?

**Comment by wprater** [comment]
I've worked around it for now.  If I decide to use your library, I'll send some examples.  Thanks for the support.
