### ISSUE TITLE
Collection Change Events

### ISSUE THREAD

**Issue by chiplay** [dhruvaray/backbone-associations#40]
I'm using Backbone Associations with some great success - thanks for the brillant extension.  One question that has come up is how to listen for colleciton changes when the collection is nested into a parent Model?  I have a model called Account, with a related subModel called Cart. Inside the Cart model is a collection of OrderItems on the Items attribute.  I'm trying to bubble up events so that when a user changes the Quantity of an OrderItem, there is a change event on the Account.Cart.Items collection.  

``` javascript
this.listenTo(RF.Models.Account,'change:Cart.Items[0].Quantity',function(){
    console.log('this works!');
});

this.listenTo(RF.Models.Account,'change:Cart.Items',function(){
    console.log('this doesn't!);
});
```

I'm trying to use BB Stickit to bind the Cart info to dom elements and have it auto-update when the OrderItems are changed, but it only refreshed when the Cart is changed directly (eg. a fetch to Account).  I've tried bind to both the Cart and Cart.Items - the later comes through Stickit just fine as a collection.  

``` javascript
bindings: {
    '#cart_btn_subtotal': {
        observe: ['Cart','Cart.Items'],
        onGet: function(values) {
            return values[0].get('ClientSubTotal');
        }
    },
    '#cart_btn_count': {
        observe: ['Cart','Cart.Items'],
        onGet: function(values) {
            return values[0].get('ItemCount');
        }
    }
}

self.stickit(RF.Models.Account);
```

Any ideas?  Thanks for the help!

**Comment by dhruvaray** [comment]
Thank you very much for the appreciation! I am glad to hear that it is useful for your work!

I'll answer your query in 2 parts. One conceptual and the other will provide you a way around your problem.

A. 
Conceptually, an add/remove or even an edit of an item in the collection does not cause the parent model which is holding the collection (via a property) to see any `change`. This is because the collection object per se has not changed. (in terms of it's memory location. Backbone (and therefore associations) uses the changed memory location to trigger change events or set `previousAttributes` etc correctly). That is why there is no changed event for the collection. Instead, the `change` event is fired for the changed item within the collection. The fully qualified event name in your example reflects this behavior.

B.
To solve your problem, here is what you would need to do while defining `Cart` which contains `CartItem`s

``` javascript
var CartItem = Backbone.AssociatedModel.extend({
    defaults:{
        qty:0
    }
});

var Cart = Backbone.AssociatedModel.extend({
    relations:[
        {
            type:Backbone.Many,
            key:'items',
            relatedModel:CartItem
        }
    ],
    defaults:{
        items:[],
        qty:0
    },

    //Simply compute new Cart qty
    updateCartQty : function(){
        if (this.get('items')){
            this.set('qty',_.reduce(this.get('items').models,function(memo, val){
                return memo + val.get('qty');
            },0));
        }
    },

    setupBindings : function(){
        this.updateCartQty();

        //Bind every item's change:qty event to update Cart qty
        _.each(this.get('items').models,function(item){
            //Remove any previous bindings
            item.off('change:qty',this.updateCartQty,this);
           //Attach bindings again
            item.on('change:qty',this.updateCartQty,this);
        },this);

    },

    initialize: function(){
        //Update cart quantity whenever items are added/removed from the collection OR
        //When the collection has been reset-ed or changed
        this.on("add:items",this.setupBindings,this);
        this.on("remove:items",this.setupBindings,this);
        this.on("reset:items",this.setupBindings,this);
        this.on("change:items",this.setupBindings,this);
    }
});

var Account = Backbone.AssociatedModel.extend({
    relations:[
        {
            type:Backbone.One,
            key:'cart',
            relatedModel:Cart
        }
    ],
    defaults:{
        cart:undefined
    }
});

```

Let's instantiate the above models and create some event handlers so that we can see what happens when items are changed or added to the collection.

``` javascript
var a = new Account();
var c = new Cart();

a.set('cart',c);

a.on('change:cart',function(){
    console.log("Account : Cart changed. Qty is "+a.get('cart').get('qty'));
});

c.on('change:qty',function(){
    console.log("Cart : Updated qty is " + c.get('qty'));
});

```

Now, onto some test cases

Scenario I : Set a new collection

``` javascript
var ci1 = new CartItem({qty:5});
var ci2 = new CartItem({qty:7});
c.set('items',[ci1,ci2]);

//console.log output
//Cart : Updated qty is 12
//Account : Cart changed. Qty is 12

```

Scenario II : Add a new item in the collection

``` javascript
var ci3 = new CartItem({qty:7});
c.get('items').add(ci3);

//console.log output
//Cart : Updated qty is 19
//Account : Cart changed. Qty is 19
```

Scenario III : Change an existing item in the collection

``` javascript
c.get('items').at(0).set('qty',10);
//console.log output
//Cart : Updated qty is 24
//Account : Cart changed. Qty is 24

```

Hope this makes it clear and provides you with a way around your problem. I haven't used Stickit, but the example shows how you can listen in to `cart` changes on `a`

**Comment by chiplay** [comment]
So good!!!! What a thoughtful and thorough explanation, it worked like charm - thank you.

I'm slowly getting used to the new system of fully qualified events, but its a really nice solution to our data model challenges and combined with StickIt, makes round tripping UI events to model changes and back to DOM elements a snap, even when they are deeply nested and associated with different views.

Side note - we're calculating a cart total by multiplying the prices of each item by their quantity and then adding the total, but due to javascript's floating point calculations the numbers often look like this: 54.34999999.  Does this look like a safe method to calculate an accurately rounded total?  (val.get('Price')

``` javascript
this.set('ClientSubTotal',_.reduce(this.get('Items').models,function(memo, val){
    return memo + ( ((val.get('Price')*100) * val.get('Quantity')) / 100 ); 
},0).toFixed(2));
```

Cheers!

**Comment by dhruvaray** [comment]
Good to know that the approach worked for you! Yes, you should be good with toFixed.

Don't forget to star us on GitHub to show your appreciation!

**Comment by dhruvaray** [comment]
With BB-Associations v0.5.0+, you could reduce the boiler plate code - which I had initially put as the answer to your question - as shown in this [recipe](http://dhruvaray.github.io/backbone-associations/recipes.html#tut-ccgp)
