### ISSUE TITLE
should expose version attribute

### ISSUE THREAD

**Issue by singingwolfboy** [dhruvaray/backbone-associations#41]
Backbone, jQuery, and many other popular libraries define a version attribute, so that the version of the library can be determined by introspection. This library should do the same, to make it easier to maintain and identify.

**Comment by jdkanani** [comment]
I am tempted to do but we have not any public container to hold this attribute like Backbone, Underscore and jQuery. Yah, we can always add like `Backbone.AssociatedModel.VERSION`, but I don't know. 
Please let us know if you have any idea.

**Comment by singingwolfboy** [comment]
`Backbone.AssociatedModel.VERSION` sounds perfectly reasonable to me -- `Backbone.AssociatedModel` _is_ the public container that this project exposes.

**Comment by dhruvaray** [comment]
@singingwolfboy : On further thought, I thought it would be better to introduce a container for associations. Rather than stick the version attribute on an element definition within the container (viz AssociatedModel). You can now get the version from Backbone.Associations.VERSION. Does this sound reasonable?

**Comment by singingwolfboy** [comment]
Sure. Would it make sense to have `Backbone.One` and `Backbone.Many` live under this new namespace, as well?
