### ISSUE TITLE
Associations with Stickit update problem

### ISSUE THREAD

**Issue by aboudreault** [dhruvaray/backbone-associations#87]
I'm trying to use Backbone Associations with stickit. Here's my model and view:

```
     var LoginModel = Backbone.AssociatedModel.extend({
       defaults: {
         username: '',
         password:'',
         errors: {
           'message': null,
           'username': null,
           'password': null
         }
       },

       relations: [
         {
           type: Backbone.One,
           key: 'errors',
           relatedModel: Backbone.AssociatedModel
         }
       ]
     });

     var LoginView = Marionette.ItemView.extend({
       el: '#login-view',
       template: '#login-template',
       model: new LoginModel(),
       bindings: {
         '#error-message': {
           observe: 'errors.message',
           update: function($el, val, model, options) {
             $el.text(val); 
           }
         }
      }

   ......
});
```

The main issue is that when I change the errors.message value with model.set(), the 'val' value of the update fonction is an empty string(or undefined). I'm checked my update fonction, and the model argument receive is not my original model of LoginModel, but the submodel 'errors' defined with my relations. Is this a normal behavior of bb associations change trigger? I can make it work with the following update function:

```
 '#error-message': {
     observe: 'errors.message',
     update: function($el, val, model, options) {
        $el.text(model.get('message')); 
       }
}
```

**Comment by aboudreault** [comment]
The issue is related to the following part...

```
       observeModelEvent(model, self, 'change:'+attr, function(model, val, options) {
              if (options == null || options.bindKey != bindKey)
                updateViewBindEl(self, $el, config, getAttr(model, modelAttr, config, self), model);
            });
```

which, doesn't care of the original _val_ argument receive and call getAttr.

**Comment by chiplay** [comment]
I'm not sure if it will help solve the issue your having here - but we've forked stickit to work better with BB Associations: https://github.com/NYTimes/backbone.stickit/pull/180

**Comment by jdkanani** [comment]
@chiplay It should work. I didn't look at stick-it code so closely but can't we just pass `val` value directly to `update` method?

@aboudreault  Here is the reason why backbone-associations doesn't work with this `getAttr` call:

``` js
// From stickit code:
observeModelEvent(model/* actual parent */,...,function(model/* changed child */, val, opts) {
  ...
});
```

Backbone-associations passes `changed model` while bubbling up events to parent models.
In callback of `observeModelEvent`, first argument will be instance of `Errors` not `LoginModel`.

That's why `$el.text(model.get('message'))` works instread of `getAttr(model, modelAttr, config, self)`.

For more discussion see [here](https://github.com/dhruvaray/backbone-associations/pull/5).

**Comment by aboudreault** [comment]
@jdkanani exact. stickit badly re-ask for the model value. That getAttr method should only use the val received, then continue its processing (onGet etc.)

**Comment by aboudreault** [comment]
@chiplay Did you open a pull request for stickit?

**Comment by jdkanani** [comment]
Or by changing 

``` js
observeModelEvent(model,...,function(model, val, opts) {
```

to

``` js
observeModelEvent(model,...,function(m /* changed this name */, val, opts) {
```

**Comment by aboudreault** [comment]
@chiplay tested your stickit, but didn't solve my issue because the observeModelEvent is still doing a model.get() call, and te model is the submodel as @jdkanani explained so the value is undefined.

**Comment by jdkanani** [comment]
@aboudreault  This one will do the trick.

``` js
// Code snippet is not tested.
observeModelEvent(model, self, 'change:'+attr, function(m, val, options) {
    if (options == null || options.bindKey != bindKey)
        updateViewBindEl(self, $el, config, getAttr(model, modelAttr, config, self), m);
    }
});
```

**Comment by aboudreault** [comment]
@jdkanani ah, well done. It works. @chiplay What applying the last change of @jdkanani in your own branch and asking for a pull request to the stickit owner? Would be something good to add to their official release.

**Comment by chiplay** [comment]
Perfect! It actually allows me to remove my checks inside the getAttr method - since the original model will always been used - regardless of whether the binding is referencing a simple attribute, associated model or associated collection.  I'm leaving my other updates to the 'change:'+attr portion of the code - as you'll need them if you ever want to use an associated collection as a stickit binding (which we're doing alot).  Hope the works!

PR: https://github.com/NYTimes/backbone.stickit/pull/180
Fork: https://github.com/chiplay/backbone.stickit/tree/bb-associations
